// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzy111RkHIOsaPJuQpInpNhgrD_n_zCXQ',
    appId: '1:543257235214:web:557aacc6d2a78d3129915f',
    messagingSenderId: '543257235214',
    projectId: 'open-nutri',
    authDomain: 'open-nutri.firebaseapp.com',
    storageBucket: 'open-nutri.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnuaxTWArVKcfGNh_G-v4tsGmDdKW7l1k',
    appId: '1:543257235214:android:ccdedee6e4d8c5ac29915f',
    messagingSenderId: '543257235214',
    projectId: 'open-nutri',
    storageBucket: 'open-nutri.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbcNnndGQVcs2B_x5Z_1wrZubyPsgE1iI',
    appId: '1:543257235214:ios:1d0d93cfa297048a29915f',
    messagingSenderId: '543257235214',
    projectId: 'open-nutri',
    storageBucket: 'open-nutri.firebasestorage.app',
    iosBundleId: 'com.example.openNutri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbcNnndGQVcs2B_x5Z_1wrZubyPsgE1iI',
    appId: '1:543257235214:ios:1d0d93cfa297048a29915f',
    messagingSenderId: '543257235214',
    projectId: 'open-nutri',
    storageBucket: 'open-nutri.firebasestorage.app',
    iosBundleId: 'com.example.openNutri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzy111RkHIOsaPJuQpInpNhgrD_n_zCXQ',
    appId: '1:543257235214:web:fd3f1cd6c6cf47a129915f',
    messagingSenderId: '543257235214',
    projectId: 'open-nutri',
    authDomain: 'open-nutri.firebaseapp.com',
    storageBucket: 'open-nutri.firebasestorage.app',
  );

}